---
name: awesome-llvm-security
project: https://github.com/gmh5225/awesome-llvm-security
tags:
- awesome
- c
- clang
- compiler
- driver
- jit
- llvm
- msvc
- obfuscate
- ollvm
- reverse-engineering
- security
- static-analysis
- windows
- windowsdriver
- x86-64
